all:
  children:
    testing:
      hosts:
        Paperless-ngx:
          ansible_host: "{{ vault_ip_paperless }}"
        SkyNet:
          ansible_host: "{{ vault_ip_skynet }}"
        Shared-Hosting:
          ansible_host: "{{ vault_ip_shared_hosting }}"
          is_swarm: true

    production:
      hosts:
        ActiveCollab:
          ansible_host: "{{ vault_ip_activecollab }}"
        T800-DB-Server:
          ansible_host: "{{ vault_ip_t800_db }}"
          has_mysql: true
        ElasticSearch:
          ansible_host: "{{ vault_ip_elastic }}"
        Nginx-Proxy-Manager:
          ansible_host: "{{ vault_ip_npm }}"
        Morkva2:
          ansible_host: "{{ vault_ip_morkva2 }}"

    infrastructure:
      hosts:
        EyeOfSauron:
          ansible_host: "{{ vault_ip_eyeofsauron }}"
          is_central: true

    specialized:
      hosts:
        PBS:
          ansible_host: "{{ vault_ip_pbs }}"
          ansible_user: "{{ vault_pbs_user }}"      
          ansible_become_pass: "{{ vault_pbs_pass }}" 
          install_method: "binary"
   
    swarm_managers:
      hosts:
        AWS-Swarm-Node: 
          ansible_host: "{{ vault_swarm_manager_ip }}"
          ansible_user: "{{ vault_aws_user }}"
          ansible_ssh_private_key_file: "{{ vault_aws_ssh_key }}"
          ansible_port: "{{ vault_aws_ssh_port }}"
          is_swarm_manager: true
