# inventories/local/hosts.yml
all:
  children:
    testing:
      hosts:
        # We use EyeOfSauron as a lab host to test all logic
        t800-lab:
          ansible_host: "{{ vault_ip_eyeofsauron }}"
          is_central: true
          install_node_exporter: true
          install_blackbox: true
