---
# roles/monitoring/handlers/main.yml

- name: Restart VictoriaMetrics
  ansible.builtin.command:
    cmd: docker compose up -d victoriametrics
    chdir: "{{ docker_compose_dir }}"
  when: is_central | default(false)

- name: Restart Grafana
  ansible.builtin.command:
    cmd: docker compose up -d grafana
    chdir: "{{ docker_compose_dir }}"
  when: is_central | default(false)

- name: Restart vmalert
  ansible.builtin.command:
    cmd: docker compose up -d vmalert
    chdir: "{{ docker_compose_dir }}"
  when: is_central | default(false)

- name: Restart Alertmanager
  ansible.builtin.command:
    cmd: docker compose up -d alertmanager
    chdir: "{{ docker_compose_dir }}"
  when: is_central | default(false)
