---
# roles/monitoring/handlers/main.yml

- name: Restart VictoriaMetrics
  ansible.builtin.command:
    cmd: docker compose restart victoriametrics
    chdir: "{{ docker_compose_dir }}"
  when: is_central | default(false)

- name: Restart Grafana
  ansible.builtin.command:
    cmd: docker compose restart grafana
    chdir: "{{ docker_compose_dir }}"
  when: is_central | default(false)

- name: Restart vmalert
  ansible.builtin.command:
    cmd: docker compose restart vmalert
    chdir: "{{ docker_compose_dir }}"
  when: is_central | default(false)

- name: Restart Alertmanager
  ansible.builtin.command:
    cmd: docker compose restart alertmanager
    chdir: "{{ docker_compose_dir }}"
  when: is_central | default(false)
